name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn docs:build

    - name: Deploy
        uses: aminzi7/github-gh-pages@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          publish_dir: docs/.vitepress/dist
